#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Better ls coloring when using solarized terminal theme
# Start by figuring out where dircolors is, by figuring out where this file is
location=$(readlink -f ${(%):-%N})
termdir="${location:h}/../.."
eval $(eval "dircolors ${location:h}/../../dircolors-solarized/dircolors.ansi-light")
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Set terminal
export TERM=xterm-256color

# Ensure that external editor launches correctly
export VISUAL='emacsclient -nw -s foo --alternate-editor='

alias vi='emacsclient -nw -s foo -a ""'
alias vim='emacsclient -nw -s foo -a ""'

# fzf setup
fzfdir="$termdir/fzf"
export PATH="$PATH:$fzfdir/bin"

[[ $- == *i* ]] && source "$fzfdir/shell/completion.zsh" 2> /dev/null

source "$fzfdir/shell/key-bindings.zsh"

# To generate paths, use default find-based command for dirs,
# and ag to find files more quickly
_fzf_compgen_path() {
  { _fzf_compgen_dir $1 & ag --hidden -g "" "$1" } 2> /dev/null
}

# Exact matching similar to helm
export FZF_DEFAULT_OPTS="-e \
   --color 16,fg:11,bg:-1,hl:1,hl+:1,bg+:7,fg+:11 \
   --color prompt:4,pointer:13,marker:13,spinner:3,info:3"

# Simply use C-f to trigger fzf; no trigger + tab
export FZF_COMPLETION_TRIGGER=''
bindkey '^F' fzf-completion
bindkey '^I' $fzf_default_completion

# Use C-g for cd completion as Alt is awkward
bindkey '^G' fzf-cd-widget

# Going up dirs is more useful than ever, since fzf only searches down!
bindkey -s '^K' 'cd ..\n'
